version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    network_mode: bridge
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cookking
      - POSTGRES_USER=cookking
      - POSTGRES_PASSWORD=cookking!@#
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - ./database/data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: bridge
    container_name: server
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
